Tests that use runInSeparateProcess fail when using php7.4 and phpdbg. To solve this, we need to upgrade the version of phpunit.
```
PHPUnit_Framework_Exception: Notice: stream_get_contents(): read of 8192 bytes failed with errno=9 Bad file descriptor in /home/travis/build/shimabox/SMBArrayto/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php(10) : eval()'d code on line 384
```